CREATE TABLE cliente(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(120) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	telefone VARCHAR(20) NOT NULL UNIQUE
		CHECK (telefone REGEXP '^[0-9]{10,15}$'),
	senha_hash VARCHAR(255) NOT NULL,
	tipo ENUM ('adm', 'funcionario', 'cliente') NOT NULL,
	endereco_id INT NOT NULL, -- FK IMPLEMENTAR
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (endereco_id)
    REFERENCES endereco(id)
    ON DELETE RESTRICT
);

CREATE TABLE pet(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    especie VARCHAR(50) NOT NULL,
    raca VARCHAR(120) NOT NULL,
    idade INT UNSIGNED NOT NULL,
    peso DECIMAL (5,2) UNSIGNED NOT NULL DEFAULT 0.00,
    foto_url VARCHAR(255),
    cliente_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (cliente_id)
    REFERENCES cliente(id)
    ON DELETE CASCADE
);

CREATE TABLE agendamento(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    data_hora DATETIME NOT NULL,
    status ENUM('agendado', 'concluido', 'cancelado') NOT NULL,
    observacoes TEXT, 
    valor DECIMAL(6,2) UNSIGNED NOT NULL DEFAULT 0.00,
    cliente_id INT UNSIGNED NOT NULL,
    pet_id INT UNSIGNED NOT NULL,
    servico_id INT UNSIGNED NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (cliente_id)
    REFERENCES cliente(id)
    ON DELETE CASCADE,
    
    FOREIGN KEY (pet_id)
    REFERENCES pet(id)
    ON DELETE CASCADE,
    
    FOREIGN KEY (servico_id)
    REFERENCES servico(id)
    ON DELETE CASCADE
);

CREATE TABLE endereco(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rua VARCHAR(120) NOT NULL,
    numero INT UNSIGNED NOT NULL,
    bairro VARCHAR(120) NOT NULL,
    cidade VARCHAR(120) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    cep VARCHAR(8) NOT NULL
		CHECK ( cep REGEXP '^[0-9]{8}$'),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE historico (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 data DATETIME NOT NULL,
 descricao TEXT,
 pet_id INT UNSIGNED NOT NULL,
 agendamento_id INT UNSIGNED NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 
 FOREIGN KEY (pet_id) 
 REFERENCES pet(id)
 ON DELETE CASCADE,
 
 FOREIGN KEY (agendamento_id)
 REFERENCES agendamento(id)
 ON DELETE CASCADE
);

CREATE TABLE servico(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao TEXT NOT NULL,
    preco_base DECIMAL(6,2) UNSIGNED NOT NULL DEFAULT 0.00,
    duracao_minutos INT UNSIGNED NOT NULL
		 CHECK (duracao_minutos BETWEEN 5 AND 480),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE produto(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao TEXT NOT NULL,
    preco DECIMAL(6,2) UNSIGNED NOT NULL DEFAULT 0.00,
    estoque INT UNSIGNED NOT NULL
		CHECK (estoque >= 0),
    categoria VARCHAR(120) NOT NULL,
    foto_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE produto_usado(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    quantidade INT UNSIGNED NOT NULL
		CHECK (quantidade >= 0),
	historico_id INT UNSIGNED NOT NULL,
    produto_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (historico_id)
    REFERENCES historico(id)
    ON DELETE CASCADE,
    
    FOREIGN KEY (produto_id)
    REFERENCES produto(id)
    ON DELETE CASCADE
);